language: python

if: branch != master

install:
  - pip3 install -U -r requirements.txt

script:
  - sphinx-build -a -b html . _build/html
  - echo "=============================="
  - ls -Ahl ./
  - echo "=============================="
  - ls -Ahl _build/html
  - echo "=============================="


deploy:
  skip_cleanup: true
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: _build/html
  target_branch: master
  keep_history: true
  committer_from_gh: true
  verbose: true
  on:
    branch: content
